// src/app/layout.tsx
import "./globals.css";

export const metadata = {
  title: "Next.js Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa">
      <body>{children}</body>
    </html>
  );
}
